baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'Brain Init Gate'
theme = 'hugo-book'

# 主题设置
enableGitInfo = true
BookRepo = 'https://github.com/FishCat233/brain-init-gate'
BookDateFormat = '2006-01-02'
# ---

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[module]
    [[module.mounts]]
        source = 'content/docs/assets'
        target = 'static/assets'