baseURL = 'https://book.whispery.top/'
languageCode = 'zh-cn'
title = 'Brain Init Gate'
theme = ['hugo-admonitions', 'hugo-book']

# 主题设置
enableGitInfo = true
# ---

[params]
math = true
BookTheme = 'auto'
BookRepo = 'https://github.com/Yiyue345/Brain.Init'
BookEditPath = 'edit/main/'
BookDateFormat = '2006-01-02'
BookPortableLinks = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
            [markup.goldmark.extensions.passthrough]
                enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                block = [['\[', '\]'], ['$$', '$$']]
                inline = [['\(', '\)'], ['$', '$']]

[module]
    [[module.mounts]]
        source = 'content/docs/assets'
        target = 'static/assets'